import type { MobileSupportedLocale } from "./mobile-locale-preference";

const messages = {
  en: ["Voice service", "Primary", "Fallback", "Enabled", "Protocol", "Endpoint", "Model", "Resource ID", "Mode", "Async two pass", "Bidirectional streaming", "Streaming input", "Authentication", "API Key", "APP ID + Access Token", "APP ID", "Send dictionary main terms as hotwords", "Hotword table name", "Hotword table ID", "Replacement table name", "Replacement table ID", "Credential", "Clear credential", "Credential configured", "No credential", "Keyless", "Save configuration", "Refresh configuration", "Test saved connection", "Check operation receipt", "Saved", "Connection succeeded", "Unable to complete the request. Review the configuration or check its operation receipt.", "Reconnect in the foreground to edit node settings. Your public draft is retained.", "Review current revision", "Configuration changed. Review the current revision before saving your retained draft.", "The supplier may truncate text beyond its token budget. Async two pass / streaming input: 5000 hotwords, 800 context tokens / 20 turns; bidirectional hotwords: 100 tokens. IDs take precedence over names.", "Recognition context", "Authorize sending these texts to the recognition service", "Only the text you enter here is sent. Chat, files, clipboard and refinement instructions are not collected. Stored privately on this device.", "Add text", "Remove text", "Save private context", "Context saved", "The configured routes do not jointly support text context. Your local text is retained and will not be submitted.", "At most 20 texts, 2 KiB UTF-8 per text, 8 KiB total. Internal line breaks are retained.", "Refinement"],
  "zh-CN": ["语音服务", "主路线", "备用路线", "启用", "协议", "端点", "模型", "资源 ID", "模式", "异步二遍", "双向流式", "流式输入", "认证", "API Key", "APP ID + Access Token", "APP ID", "发送词典主词作为热词", "热词表名称", "热词表 ID", "替换词表名称", "替换词表 ID", "凭据", "清除凭据", "已配置凭据", "未配置凭据", "无密钥", "保存配置", "刷新配置", "测试已保存连接", "查询操作回执", "已保存", "连接成功", "请求未完成。请检查配置或查询操作回执。", "请在前台重新连接后编辑节点设置。公开草稿会保留。", "确认当前版本", "配置已变化，请确认当前版本后保存保留的草稿。", "供应商可能截断超出 token 预算的文本。二遍/流式输入：5000 热词、800 语境 tokens/20 轮；双向热词：100 tokens。ID 优先于名称。", "识别语境", "授权将这些文本发送给识别服务", "只发送在此填写的内容。不收集聊天、文件、剪贴板或润色指令。仅保存在本机。", "添加文本", "删除文本", "保存本机语境", "语境已保存", "已配置主备路线未共同支持文本语境。本机文本会保留且不会提交。", "最多20项，每项2 KiB UTF-8，总计8 KiB，保留内部换行。", "润色"],
  "zh-TW": ["語音服務", "主要路線", "備用路線", "啟用", "協定", "端點", "模型", "資源 ID", "模式", "非同步二遍", "雙向串流", "串流輸入", "驗證", "API Key", "APP ID + Access Token", "APP ID", "傳送詞典主詞作為熱詞", "熱詞表名稱", "熱詞表 ID", "替換詞表名稱", "替換詞表 ID", "憑證", "清除憑證", "已設定憑證", "未設定憑證", "無金鑰", "儲存設定", "重新整理設定", "測試已儲存連線", "查詢操作回執", "已儲存", "連線成功", "請求未完成。請檢查設定或查詢操作回執。", "請在前景重新連線後編輯節點設定。公開草稿會保留。", "確認目前版本", "設定已變更，請確認目前版本後儲存保留的草稿。", "供應商可能截斷超過 token 預算的文字。二遍/串流輸入：5000 熱詞、800 語境 tokens/20 輪；雙向熱詞：100 tokens。ID 優先於名稱。", "識別語境", "授權將這些文字傳送給識別服務", "只傳送在此填寫的內容。不收集聊天、檔案、剪貼簿或潤色指令。僅儲存在本機。", "新增文字", "刪除文字", "儲存本機語境", "語境已儲存", "已設定主備路線未共同支援文字語境。本機文字會保留且不會提交。", "最多20項，每項2 KiB UTF-8，總計8 KiB，保留內部換行。", "潤色"],
  ja: ["音声サービス", "メイン", "予備", "有効", "プロトコル", "エンドポイント", "モデル", "リソース ID", "モード", "非同期二段階", "双方向ストリーミング", "ストリーム入力", "認証", "API Key", "APP ID + Access Token", "APP ID", "辞書の主語句をホットワードとして送信", "ホットワード表名", "ホットワード表 ID", "置換表名", "置換表 ID", "認証情報", "認証情報を削除", "認証情報設定済み", "認証情報なし", "キー不要", "設定を保存", "設定を再取得", "保存済み接続をテスト", "操作結果を確認", "保存しました", "接続成功", "リクエストを完了できません。設定または操作結果を確認してください。", "前面で再接続すると編集できます。公開設定の下書きは保持されます。", "現在の版を確認", "設定が変更されました。現在の版を確認してから下書きを保存してください。", "提供元は token 上限を超えるテキストを切り詰める場合があります。二段階/入力：5000語、文脈800 tokens/20ターン。双方向ホットワード：100 tokens。IDが名前より優先されます。", "認識用の文脈", "このテキストを認識サービスに送信することを許可", "ここに入力した内容だけを送信します。チャット、ファイル、クリップボード、校正指示は収集しません。この端末だけに保存します。", "テキストを追加", "テキストを削除", "端末の文脈を保存", "文脈を保存しました", "設定済みルートは共通の文脈機能をサポートしていません。端末のテキストを保持し、送信しません。", "最大20件、各2 KiB UTF-8、合計8 KiB。内部の改行を保持します。", "校正"],
  ko: ["음성 서비스", "기본", "대체", "사용", "프로토콜", "엔드포인트", "모델", "리소스 ID", "모드", "비동기 2단계", "양방향 스트리밍", "스트림 입력", "인증", "API Key", "APP ID + Access Token", "APP ID", "사전 기본 용어를 핫워드로 전송", "핫워드 표 이름", "핫워드 표 ID", "대체 표 이름", "대체 표 ID", "자격 증명", "자격 증명 삭제", "자격 증명 설정됨", "자격 증명 없음", "키 없음", "설정 저장", "설정 새로 고침", "저장된 연결 테스트", "작업 결과 조회", "저장됨", "연결 성공", "요청을 완료하지 못했습니다. 설정 또는 작업 결과를 확인하세요.", "전경에서 다시 연결하면 노드 설정을 편집할 수 있습니다. 공개 초안은 유지됩니다.", "현재 버전 확인", "설정이 변경되었습니다. 현재 버전을 확인한 후 초안을 저장하세요.", "공급자는 token 예산을 넘은 텍스트를 자를 수 있습니다. 2단계/입력: 핫워드5000개, 문맥800 tokens/20턴. 양방향 핫워드:100 tokens. ID가 이름보다 우선합니다.", "인식 문맥", "이 텍스트를 인식 서비스에 보내도록 허용", "여기에 입력한 내용만 보냅니다. 채팅, 파일, 클립보드, 다듬기 지침을 수집하지 않습니다. 이 기기에만 저장합니다.", "텍스트 추가", "텍스트 삭제", "기기 문맥 저장", "문맥 저장됨", "설정된 경로가 공통 문맥 기능을 지원하지 않습니다. 기기 텍스트를 유지하고 제출하지 않습니다.", "최대20개, 항목당2 KiB UTF-8, 총8 KiB. 내부 줄바꿈을 유지합니다.", "다듬기"]
} satisfies Record<MobileSupportedLocale, readonly string[]>;

export function mobileVoiceServiceMessage(locale: MobileSupportedLocale, index: number): string {
  return messages[locale][index] ?? messages.en[index] ?? "";
}
