import type { MobileRemoteDesktopViewerCommand } from "./remote-desktop-controller";

const RTC_NETWORK = Object.freeze({
  maxCandidates: 128,
  batchSize: 16,
  pollMs: 250,
  exchangeMs: 30_000,
  disconnectedMs: 5_000,
  answerMs: 45_000,
  connectMs: 15_000,
  stableMs: 30_000,
  retryMs: Object.freeze([1_000, 3_000, 8_000])
});

const KEY_CODES = Object.freeze([
  ..."ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map((key) => `Key${key}`),
  ..."0123456789".split("").map((key) => `Digit${key}`),
  ...Array.from({ length: 12 }, (_value, index) => `F${index + 1}`),
  "Enter", "Escape", "Tab", "Space", "Backspace", "Delete", "Insert", "Home", "End",
  "PageUp", "PageDown", "ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight", "ShiftLeft",
  "ControlLeft", "AltLeft", "MetaLeft", "Minus", "Equal", "BracketLeft", "BracketRight",
  "Backslash", "Semicolon", "Quote", "Backquote", "Comma", "Period", "Slash"
]);

export function remoteDesktopViewerHtml(surface: string, foreground: string): string {
  const background = color(surface, "#15191d");
  const ink = color(foreground, "#f4f4f2");
  return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; media-src blob:; connect-src 'none'"><style>
  *{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:${background};touch-action:none;overscroll-behavior:none;-webkit-user-select:none;user-select:none}#stage{position:absolute;inset:0;overflow:hidden}video,img{position:absolute;max-width:none;pointer-events:none;transform-origin:0 0;border:0;outline:0}video{display:none;z-index:2}#image{z-index:1}img:not([src]){visibility:hidden}#cursor{position:absolute;z-index:3;width:18px;height:18px;border:2px solid ${ink};border-radius:50%;transform:translate(-50%,-50%);display:none;pointer-events:none}#cursor-image{position:absolute;inset:0;width:100%;height:100%}#keyboard{position:absolute;left:0;bottom:0;width:1px;height:1px;opacity:.01;font-size:16px;pointer-events:none;border:0;padding:0}
  </style></head><body><div id="stage"><img id="image" alt=""><video id="video" autoplay muted playsinline></video><div id="cursor"><img id="cursor-image" alt=""></div></div><textarea id="keyboard" autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" aria-label="Keyboard"></textarea><script>
const net=${JSON.stringify(RTC_NETWORK)},validKeys=new Set(${JSON.stringify(KEY_CODES)});
${VIEWER_SCRIPT}
</script></body></html>`;
}

export function remoteDesktopViewerCommand(message: MobileRemoteDesktopViewerCommand): string {
  const value = JSON.stringify(message).replace(/</gu, "\\u003c").replace(/\u2028/gu, "\\u2028").replace(/\u2029/gu, "\\u2029");
  return `window.__jokoRemoteDesktop&&window.__jokoRemoteDesktop.receive(${value});true;`;
}

function color(value: string, fallback: string): string {
  return /^#[0-9a-f]{3,8}$/iu.test(value) ? value : fallback;
}

const VIEWER_SCRIPT = String.raw`
(()=>{
  const stage=document.getElementById('stage'),image=document.getElementById('image'),video=document.getElementById('video');
  const cursor=document.getElementById('cursor'),cursorImage=document.getElementById('cursor-image'),keyboard=document.getElementById('keyboard');
  let epoch=null,dw=1920,dh=1080,zoom=1,panX=0,panY=0,mode='touch',control=false;
  let pc=null,dc=null,attemptId=null,generation=0,retries=0,videoPresented=false,configPending=false;
  let deadline=null,disconnectTimer=null,retryTimer=null,stableTimer=null,iceTimer=null;
  let localCandidates=[],localAck=0,remoteAfter=0,remoteComplete=false,remoteSeen=new Set(),icePending=null,exchangeId=0,exchangeUntil=0;
  let seq=0,sequenceLimit=Number.MAX_SAFE_INTEGER,pending=[],sending=false,drag=false,hold=null,start=null,last=null,multi=null,gestureFrame=null;
  const pointers=new Map();let cx=.5,cy=.5,composing=false,keyboardEnabled=false;
  let remoteCursor=null,cursorOverlay=false,lastLocalMove=0,localCursorAwake=false,localCursorTimer=null,localCursorGeneration=0;
  const post=message=>window.ReactNativeWebView.postMessage(JSON.stringify({...message,epoch}));
  const clamp=value=>Math.max(0,Math.min(1,value));
  function layout(){const sw=stage.clientWidth,sh=stage.clientHeight,scale=Math.min(sw/dw,sh/dh)*zoom,w=dw*scale,h=dh*scale;return{w,h,x:(sw-w)/2+panX,y:(sh-h)/2+panY};}
  function boundPan(){const r=layout(),margin=zoom>1?80:0;const minX=Math.min(0,stage.clientWidth-r.w)-margin,maxX=Math.max(0,stage.clientWidth-r.w)+margin;const minY=Math.min(0,stage.clientHeight-r.h)-margin,maxY=Math.max(0,stage.clientHeight-r.h)+margin;panX=Math.max(minX,Math.min(maxX,panX));panY=Math.max(minY,Math.min(maxY,panY));}
  function render(){const r=layout();for(const el of [image,video]){el.style.width=r.w+'px';el.style.height=r.h+'px';el.style.left=r.x+'px';el.style.top=r.y+'px';}if(remoteCursor){cursor.style.width=remoteCursor.width+'px';cursor.style.height=remoteCursor.height+'px';cursor.style.border='0';cursor.style.borderRadius='0';cursor.style.transform='none';cursor.style.left=(r.x+cx*r.w-remoteCursor.hotX)+'px';cursor.style.top=(r.y+cy*r.h-remoteCursor.hotY)+'px';cursor.style.display='block';cursor.style.opacity=(remoteCursor.visible||(control&&mode==='trackpad'&&localCursorAwake))?'1':'0';}else{cursor.style.opacity='1';cursor.style.width='18px';cursor.style.height='18px';cursor.style.border='';cursor.style.borderRadius='';cursor.style.transform='';cursor.style.left=(r.x+cx*r.w)+'px';cursor.style.top=(r.y+cy*r.h)+'px';cursor.style.display=!cursorOverlay&&control&&mode==='trackpad'?'block':'none';}}
  function validCursorPng(value){if(typeof value!=='string'||value.length>65536||!/^iVBORw0KGgo[A-Za-z0-9+/]*={0,2}$/.test(value))return false;let bytes;try{bytes=atob(value);}catch{return false;}if(bytes.length<33||bytes.length>49152||bytes.charCodeAt(8)!==0||bytes.charCodeAt(9)!==0||bytes.charCodeAt(10)!==0||bytes.charCodeAt(11)!==13||bytes.slice(12,16)!=='IHDR')return false;const dimension=offset=>bytes.charCodeAt(offset)*0x1000000+bytes.charCodeAt(offset+1)*0x10000+bytes.charCodeAt(offset+2)*0x100+bytes.charCodeAt(offset+3),width=dimension(16),height=dimension(20);return width>=1&&width<=512&&height>=1&&height<=512;}
  function validCursor(value){const keys=value&&typeof value==='object'&&!Array.isArray(value)?Object.keys(value):[];return keys.length===8&&['visible','x','y','width','height','hotX','hotY','png'].every(key=>Object.prototype.hasOwnProperty.call(value,key))&&typeof value.visible==='boolean'&&[value.x,value.y,value.width,value.height,value.hotX,value.hotY].every(Number.isFinite)&&value.x>=0&&value.x<=1&&value.y>=0&&value.y<=1&&value.width>0&&value.width<=256&&value.height>0&&value.height<=256&&value.hotX>=0&&value.hotX<=value.width&&value.hotY>=0&&value.hotY<=value.height&&validCursorPng(value.png);}
  function clearLocalCursorTimer(){clearTimeout(localCursorTimer);localCursorTimer=null;localCursorGeneration++;localCursorAwake=false;}
  function noteLocalCursorActivity(){lastLocalMove=performance.now();if(mode!=='trackpad')return;localCursorAwake=true;clearTimeout(localCursorTimer);const token=++localCursorGeneration,cursorEpoch=epoch;localCursorTimer=setTimeout(()=>{if(token!==localCursorGeneration||epoch!==cursorEpoch)return;localCursorTimer=null;localCursorAwake=false;if(remoteCursor){cx=remoteCursor.x;cy=remoteCursor.y;}render();},205);}
  function receiveCursor(value){if(value===null){cursorOverlay=true;remoteCursor=null;clearLocalCursorTimer();cursorImage.removeAttribute('src');render();return;}if(!validCursor(value))return;cursorOverlay=true;if(!remoteCursor||remoteCursor.png!==value.png)cursorImage.src='data:image/png;base64,'+value.png;if(!control||mode!=='trackpad'||(!pointers.size&&performance.now()-lastLocalMove>200)){cx=value.x;cy=value.y;}if(value.visible)localCursorAwake=false;remoteCursor=value;render();}
  function resetCursor(){remoteCursor=null;clearLocalCursorTimer();cursorImage.removeAttribute('src');render();}
  function point(p){const r=layout();return{x:clamp((p.x-r.x)/r.w),y:clamp((p.y-r.y)/r.h)};}
  function inside(p){const r=layout();return p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h;}
  function pan(dx,dy){panX+=dx;panY+=dy;boundPan();render();}
  function queue(event){if(!control)return;if(event.kind==='key'||event.kind==='text'){localCursorAwake=false;render();}if(event.kind==='move'||event.kind==='button')noteLocalCursorActivity();const tail=pending[pending.length-1];if(event.kind==='move'&&tail?.kind==='move')pending[pending.length-1]=event;else if(event.kind==='scroll'&&tail?.kind==='scroll'){tail.dx=Math.max(-2000,Math.min(2000,tail.dx+event.dx));tail.dy=Math.max(-2000,Math.min(2000,tail.dy+event.dy));}else pending.push(event);if(pending.length>64){pending=[{kind:'release'}];control=false;post({type:'inputOverflow'});}}
  function flush(){if(!pending.length||sending)return;if(seq>=sequenceLimit){pending=[];control=false;post({type:'inputOverflow'});render();return;}const events=pending.splice(0,64),sequence=++seq;if(pc?.connectionState==='connected'&&dc?.readyState==='open'&&dc.bufferedAmount<16384)dc.send(JSON.stringify({sequence,events}));else{sending=true;post({type:'input',sequence,events});}}
  setInterval(flush,33);
  function click(button=0){queue({kind:'button',button,down:true,x:cx,y:cy});queue({kind:'button',button,down:false,x:cx,y:cy});flush();}
  function release(){clearTimeout(hold);if(gestureFrame!==null)cancelAnimationFrame(gestureFrame);gestureFrame=null;if(control){queue({kind:'release'});flush();}drag=false;pointers.clear();start=last=multi=null;}
  function pair(){const [a,b]=[...pointers.values()];return{x:(a.x+b.x)/2,y:(a.y+b.y)/2,d:Math.hypot(a.x-b.x,a.y-b.y)};}
  function movePair(){gestureFrame=null;if(pointers.size<2||!multi)return;const next=pair(),span=Math.abs(next.d-multi.d),travel=Math.hypot(next.x-multi.x,next.y-multi.y);if(!multi.kind){if(span>8&&span>travel*.7)multi.kind='pinch';else if(travel>8)multi.kind='scroll';}if(multi.kind==='pinch'){zoom=Math.max(1,Math.min(5,multi.zoom*next.d/Math.max(1,multi.d)));boundPan();render();}else if(multi.kind==='scroll'){const dx=next.x-multi.lastX,dy=next.y-multi.lastY;if(control&&mode!=='pan')queue({kind:'scroll',dx:Math.max(-2000,Math.min(2000,-dx)),dy:Math.max(-2000,Math.min(2000,-dy))});else pan(dx,dy);}multi.lastX=next.x;multi.lastY=next.y;}
  stage.addEventListener('pointerdown',event=>{event.preventDefault();stage.setPointerCapture(event.pointerId);pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.size===1){start=last={x:event.clientX,y:event.clientY};hold=setTimeout(()=>{if(control&&mode!=='pan'&&pointers.size===1&&start&&(mode!=='touch'||inside(start))){if(mode==='touch'){const p=point(start);cx=p.x;cy=p.y;}queue({kind:'button',button:0,down:true,x:cx,y:cy});flush();drag=true;}},400);}else{clearTimeout(hold);if(drag)queue({kind:'release'});drag=false;start=null;const p=pair();multi={...p,lastX:p.x,lastY:p.y,zoom,kind:null};}});
  stage.addEventListener('pointermove',event=>{if(!pointers.has(event.pointerId))return;event.preventDefault();pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.size>=2){if(gestureFrame===null)gestureFrame=requestAnimationFrame(movePair);return;}if(!start||!last)return;const now={x:event.clientX,y:event.clientY},dx=now.x-last.x,dy=now.y-last.y;last=now;if(Math.hypot(now.x-start.x,now.y-start.y)>6)clearTimeout(hold);if(!control||mode==='pan'||(mode==='touch'&&!drag)){pan(dx,dy);return;}if(mode==='trackpad'){const r=layout();cx=clamp(cx+dx/r.w*1.5);cy=clamp(cy+dy/r.h*1.5);}else{const p=point(now);cx=p.x;cy=p.y;}queue({kind:'move',x:cx,y:cy});render();});
  function pointerUp(event){if(!pointers.has(event.pointerId))return;clearTimeout(hold);const wasTap=start&&last&&Math.hypot(last.x-start.x,last.y-start.y)<=6;pointers.delete(event.pointerId);if(drag){queue({kind:'button',button:0,down:false,x:cx,y:cy});flush();drag=false;}else if(wasTap&&control&&mode!=='pan'&&event.type==='pointerup'&&(mode!=='touch'||inside({x:event.clientX,y:event.clientY}))){if(mode==='touch'){const p=point({x:event.clientX,y:event.clientY});cx=p.x;cy=p.y;}click();}start=last=multi=null;boundPan();render();}
  stage.addEventListener('pointerup',pointerUp);stage.addEventListener('pointercancel',()=>{release();boundPan();render();});
  stage.addEventListener('contextmenu',event=>event.preventDefault());stage.addEventListener('selectstart',event=>event.preventDefault());stage.addEventListener('dragstart',event=>event.preventDefault());
  const sentinel='\u200b';function resetKeyboard(){keyboard.value=sentinel;keyboard.setSelectionRange(1,1);}function showKeyboard(enabled){keyboardEnabled=enabled&&control;if(!keyboardEnabled){composing=false;resetKeyboard();keyboard.blur();return;}keyboard.blur();resetKeyboard();keyboard.focus({preventScroll:true});}
  function keyboardKey(code){if(!keyboardEnabled||!control)return;queue({kind:'key',code,down:true});queue({kind:'key',code,down:false});flush();}
  function commitKeyboard(){if(!keyboardEnabled||!control||composing)return;const text=keyboard.value.replace(sentinel,'');if(text){for(let index=0;index<text.length;index+=4096)queue({kind:'text',text:text.slice(index,index+4096)});flush();}resetKeyboard();}
  keyboard.addEventListener('compositionstart',()=>{composing=true;});keyboard.addEventListener('compositionend',()=>{composing=false;commitKeyboard();});keyboard.addEventListener('input',event=>{if(!event.isComposing)commitKeyboard();});keyboard.addEventListener('beforeinput',event=>{if(composing||event.isComposing)return;if(event.inputType==='deleteContentBackward'){event.preventDefault();keyboardKey('Backspace');}else if(event.inputType==='insertLineBreak'||event.inputType==='insertParagraph'){event.preventDefault();keyboardKey('Enter');}});
  const normalizedKey=code=>/^(Shift|Control|Alt|Meta)Right$/.test(code)?code.replace(/Right$/,'Left'):code;
  document.addEventListener('keydown',event=>{const code=normalizedKey(event.code);if(control&&validKeys.has(code)){event.preventDefault();queue({kind:'key',code,down:true});}});document.addEventListener('keyup',event=>{const code=normalizedKey(event.code);if(control&&validKeys.has(code)){event.preventDefault();queue({kind:'key',code,down:false});}});window.addEventListener('blur',release);new ResizeObserver(()=>{release();boundPan();render();}).observe(stage);
  function retainFrame(){if(!videoPresented||video.readyState<2||!video.videoWidth||!video.videoHeight)return;const canvas=document.createElement('canvas');try{const scale=Math.min(1,1280/Math.max(video.videoWidth,video.videoHeight));canvas.width=Math.max(1,Math.round(video.videoWidth*scale));canvas.height=Math.max(1,Math.round(video.videoHeight*scale));const context=canvas.getContext('2d');if(context){context.drawImage(video,0,0,canvas.width,canvas.height);image.src=canvas.toDataURL('image/jpeg',.7);}}catch{}finally{canvas.width=canvas.height=0;}}
  function presentationActive(){return video.webkitPresentationMode==='picture-in-picture'||document.pictureInPictureElement===video;}
  function presentationSupported(){try{return video.webkitSupportsPresentationMode?.('picture-in-picture')===true||document.pictureInPictureEnabled===true;}catch{return false;}}
  function reportPresentation(){post({type:'presentation',active:presentationActive()});}
  async function setPresentation(enabled){try{if(enabled){if(video.webkitSupportsPresentationMode?.('picture-in-picture'))video.webkitSetPresentationMode('picture-in-picture');else if(document.pictureInPictureEnabled&&video.requestPictureInPicture)await video.requestPictureInPicture();else throw new Error();}else if(video.webkitPresentationMode==='picture-in-picture')video.webkitSetPresentationMode('inline');else if(document.pictureInPictureElement===video&&document.exitPictureInPicture)await document.exitPictureInPicture();}catch{post({type:'presentationFailed'});}}
  video.addEventListener('webkitpresentationmodechanged',reportPresentation);video.addEventListener('enterpictureinpicture',reportPresentation);video.addEventListener('leavepictureinpicture',reportPresentation);
  function clearRtcTimers(){for(const timer of [deadline,disconnectTimer,retryTimer,stableTimer,iceTimer])clearTimeout(timer);deadline=disconnectTimer=retryTimer=stableTimer=iceTimer=null;}
  function closeRtc(preserve=true){configPending=false;if(preserve)retainFrame();generation++;clearRtcTimers();localCandidates=[];localAck=remoteAfter=0;remoteComplete=false;remoteSeen=new Set();icePending=null;attemptId=null;if(dc)dc.close();if(pc)pc.close();dc=pc=null;video.srcObject=null;video.style.display='none';videoPresented=false;image.style.display='block';if(!preserve)image.removeAttribute('src');}
  function failRtc(reason,canRetry=true){const failed=attemptId;release();sending=false;pending=[];closeRtc();post({type:'fallback',attemptId:failed,reason});if(canRetry&&epoch&&retries<net.retryMs.length){const delay=net.retryMs[retries++];retryTimer=setTimeout(()=>{retryTimer=null;if(epoch)connect();},delay);}}
  function pollIce(){if(!pc||!pc.remoteDescription||icePending||Date.now()>=exchangeUntil)return;const candidates=localCandidates.slice(localAck,localAck+net.batchSize);icePending={after:remoteAfter,sent:candidates.length,exchangeId:++exchangeId};post({type:'ice',attemptId,candidates,after:remoteAfter,exchangeId});iceTimer=setTimeout(()=>{icePending=null;pollIce();},4500);}
  async function receiveIce(message){if(!pc||!icePending||message.attemptId!==attemptId||message.exchangeId!==icePending.exchangeId)return;const rtc=pc,g=generation,batch=icePending;clearTimeout(iceTimer);try{if(message.error){icePending=null;iceTimer=setTimeout(pollIce,1000);return;}if(!Array.isArray(message.candidates)||message.candidates.length>net.batchSize||message.next!==batch.after+message.candidates.length||message.next>net.maxCandidates)throw new Error();for(const candidate of message.candidates){if(g!==generation)return;const key=JSON.stringify(candidate);if(remoteSeen.has(key))continue;if(remoteSeen.size>=net.maxCandidates)throw new Error();await rtc.addIceCandidate(candidate);remoteSeen.add(key);}if(g!==generation)return;localAck+=batch.sent;remoteAfter=message.next;remoteComplete=message.complete===true;icePending=null;if(!(remoteComplete&&rtc.iceGatheringState==='complete'&&localAck===localCandidates.length))iceTimer=setTimeout(pollIce,net.pollMs);}catch{if(g===generation)failRtc('candidates');}}
  async function receiveAnswer(message){if(!pc||message.attemptId!==attemptId)return;const rtc=pc,g=generation;try{await rtc.setRemoteDescription({type:'answer',sdp:message.sdp});if(g!==generation)return;clearTimeout(deadline);deadline=setTimeout(()=>{if(g===generation&&rtc.connectionState!=='connected')failRtc('connect-timeout');},net.connectMs);exchangeUntil=Date.now()+net.exchangeMs;pollIce();}catch{if(g===generation)failRtc('answer');}}
  async function connect(){closeRtc();const g=generation;attemptId=String(g);post({type:'iceConfig',attemptId});if(!window.RTCPeerConnection){failRtc('unsupported',false);return;}configPending=true;deadline=setTimeout(()=>{if(g===generation&&configPending){configPending=false;void startRtc(g,[{urls:['stun:stun.cloudflare.com:3478']},{urls:['stun:stun.l.google.com:19302']}]);}},3500);}
  async function startRtc(g,iceServers){try{const rtc=new RTCPeerConnection({iceServers});pc=rtc;dc=rtc.createDataChannel('input-v1',{ordered:true});rtc.addTransceiver('video',{direction:'recvonly'});rtc.addTransceiver('audio',{direction:'recvonly'});dc.onmessage=event=>{try{if(g!==generation||pc!==rtc||typeof event.data!=='string'||event.data.length>80000)return;const message=JSON.parse(event.data);if(message.type==='cursor'&&Object.prototype.hasOwnProperty.call(message,'cursor'))receiveCursor(message.cursor);else if(presentationActive()&&message.type==='viewPing'&&typeof message.challenge==='string'&&message.challenge.length<=64&&dc?.readyState==='open')dc.send(message.challenge);}catch{}};rtc.onicecandidate=({candidate})=>{if(g!==generation||!candidate?.candidate)return;if(localCandidates.length>=net.maxCandidates){failRtc('candidate-limit',false);return;}localCandidates.push({candidate:candidate.candidate,sdpMid:candidate.sdpMid,sdpMLineIndex:candidate.sdpMLineIndex,...(candidate.usernameFragment?{usernameFragment:candidate.usernameFragment}:{})});};rtc.ontrack=event=>{if(g!==generation)return;const current=video.srcObject instanceof MediaStream?video.srcObject:null;if(current&&!event.streams[0])current.addTrack(event.track);else video.srcObject=event.streams[0]||new MediaStream([event.track]);video.play().catch(()=>{});};video.onplaying=()=>{if(g!==generation||videoPresented)return;videoPresented=true;video.style.display='block';render();post({type:'pipCapability',supported:presentationSupported()});requestAnimationFrame(()=>requestAnimationFrame(()=>{if(g!==generation)return;post({type:'streaming',attemptId});}));};rtc.onconnectionstatechange=()=>{if(g!==generation)return;if(['failed','closed'].includes(rtc.connectionState)){failRtc('transport');return;}if(rtc.connectionState==='disconnected'){clearTimeout(stableTimer);if(!disconnectTimer){release();post({type:'reconnecting',attemptId});disconnectTimer=setTimeout(()=>{if(g===generation)failRtc('disconnected');},net.disconnectedMs);}}else if(rtc.connectionState==='connected'){clearTimeout(disconnectTimer);disconnectTimer=null;clearTimeout(deadline);if(videoPresented)post({type:'streaming',attemptId});stableTimer=setTimeout(()=>{if(g===generation)retries=0;},net.stableMs);}};await rtc.setLocalDescription(await rtc.createOffer());if(g!==generation)return;post({type:'offer',attemptId,sdp:rtc.localDescription.sdp});deadline=setTimeout(()=>{if(g===generation)failRtc('answer-timeout');},net.answerMs);}catch{if(g===generation)failRtc('setup');}}
  async function receiveIceConfig(message){if(!epoch||!configPending||message.attemptId!==attemptId)return;configPending=false;clearTimeout(deadline);deadline=null;await startRtc(generation,message.iceServers);}
  function receive(message){if(!message||typeof message!=='object')return;switch(message.type){case'init':release();cursorOverlay=message.cursorOverlay===true;resetCursor();pending=[];sending=false;seq=Number.isSafeInteger(message.sequenceBase)&&message.sequenceBase>=0?message.sequenceBase:0;sequenceLimit=Number.isSafeInteger(message.sequenceLimit)&&message.sequenceLimit>seq?message.sequenceLimit:Number.MAX_SAFE_INTEGER;epoch=message.epoch;dw=message.width;dh=message.height;zoom=1;panX=panY=0;video.muted=message.audio!==true;retries=0;render();if(message.webrtc===false){closeRtc();post({type:'fallback',attemptId:null,reason:'unavailable'});}else connect();break;case'answer':if(message.epoch===epoch)void receiveAnswer(message);break;case'iceConfig':if(message.epoch===epoch)void receiveIceConfig(message);break;case'ice':if(message.epoch===epoch)void receiveIce(message);break;case'fallback':if(message.epoch===epoch&&message.attemptId===attemptId)failRtc('host',message.retry!==false);break;case'frame':{if(message.epoch!==epoch||typeof message.frameId!=='string')break;if(Object.prototype.hasOwnProperty.call(message,'cursor'))receiveCursor(message.cursor);else resetCursor();const frameEpoch=epoch,frameId=message.frameId;image.onload=()=>{if(epoch===frameEpoch)post({type:'framePresented',frameId,presented:true});};image.onerror=()=>{if(epoch===frameEpoch)post({type:'framePresented',frameId,presented:false});};image.src='data:image/jpeg;base64,'+message.jpeg;break;}case'control':release();sending=false;pending=[];control=message.enabled===true;if(!control)showKeyboard(false);render();break;case'mode':release();mode=message.mode;render();break;case'fit':zoom=1;panX=panY=0;render();break;case'keyboard':showKeyboard(message.enabled===true);break;case'click':if(message.button===0||message.button===1||message.button===2)click(message.button);break;case'releaseInput':sending=false;pending=[];release();break;case'events':for(const event of message.events||[])queue(event);flush();break;case'ack':if(message.epoch===epoch&&message.sequence===seq)sending=false;break;case'videoSettings':video.muted=message.audio!==true;retries=0;connect();break;case'presentation':void setPresentation(message.enabled===true);break;case'stop':void setPresentation(false);showKeyboard(false);control=false;release();resetCursor();cursorOverlay=false;pending=[];sending=false;epoch=null;closeRtc(message.preserveFrame===true);render();break;}}
  window.__jokoRemoteDesktop={receive};window.addEventListener('message',event=>{try{receive(typeof event.data==='string'?JSON.parse(event.data):event.data);}catch{}});document.addEventListener('message',event=>{try{receive(typeof event.data==='string'?JSON.parse(event.data):event.data);}catch{}});render();post({type:'ready'});
})();`;

export const mobileRemoteDesktopViewerTesting = Object.freeze({ RTC_NETWORK, KEY_CODES });
