/** Standard capability identifiers shared by public contracts and capability-driven clients. */
export const capabilityNames = {
  sessionDiscovery: "session.discovery",
  sessionCatalog: "session.catalog",
  sessionAutoTitle: "session.auto_title",
  sessionAiRename: "session.ai_rename",
  sessionSummary: "session.summary",
  sessionResume: "session.resume",
  sessionDetach: "session.detach",
  sessionFork: "session.fork",
  sessionRewind: "session.rewind",
  sessionTree: "session.tree",
  sessionMessageDelete: "session.message_delete",
  sessionReset: "session.reset",
  reviewIsolated: "review.isolated",
  turnStream: "turn.stream",
  turnAbort: "turn.abort",
  turnGracefulStop: "turn.graceful_stop",
  turnSteer: "turn.steer",
  turnFollowUp: "turn.follow_up",
  queueCancel: "queue.cancel",
  queueEdit: "queue.edit",
  queueReorder: "queue.reorder",
  queuePause: "queue.pause",
  inputText: "input.text",
  inputImage: "input.image",
  inputFile: "input.file",
  inputMention: "input.mention",
  voiceInput: "input.voice",
  remoteHostCatalog: "remote_host.catalog",
  remoteHostManagement: "remote_host.management",
  remoteHostConnectionControl: "remote_host.connection_control",
  remoteHostConnectionTest: "remote_host.connection_test",
  remoteHostTrustReset: "remote_host.trust_reset",
  remoteHostCommandExecution: "remote_host.command_execution",
  remoteHostProcessStreaming: "remote_host.process_streaming",
  remoteHostFileTransfer: "remote_host.file_transfer",
  remoteHostTcpForwarding: "remote_host.tcp_forwarding",
  modelList: "model.list",
  modelSwitch: "model.switch",
  modelEffort: "model.effort",
  modelFastMode: "model.fast_mode",
  modelPricing: "model.pricing",
  providerManagedCatalog: "provider.managed_catalog",
  providerAccountUsage: "provider.account_usage",
  permissionModes: "permission.modes",
  permissionChange: "permission.change",
  planMode: "plan_mode",
  contextUsage: "context.usage",
  contextCompact: "context.compact",
  sessionExport: "session.export",
  workspaceFiles: "workspace.files",
  workspaceFilesWatch: "workspace.files.watch",
  workspaceFilesWrite: "workspace.files.write",
  workspaceDiff: "workspace.diff",
  workspaceGeneratedFiles: "workspace.generated_files",
  workspaceDiffSources: "workspace.diff.sources",
  workspaceDiffImagePreview: "workspace.diff.image_preview",
  workspaceDiffStage: "workspace.diff.stage",
  workspaceDiffUnstage: "workspace.diff.unstage",
  workspaceDiffRevert: "workspace.diff.revert",
  workspaceDiffCommit: "workspace.diff.commit",
  workspaceDiffPush: "workspace.diff.push",
  workspaceRewind: "workspace.rewind",
  workspaceExtraDirs: "workspace.extra_dirs",
  interactionPermission: "interaction.permission",
  interactionQuestion: "interaction.question",
  interactionPlanReview: "interaction.plan_review",
  backgroundTasks: "background.tasks",
  backgroundTasksCancel: "background.tasks.cancel",
  subagentsList: "subagents.list",
  subagentsDetail: "subagents.detail",
  subagentsTranscript: "subagents.transcript",
  subagentsStop: "subagents.stop",
  subagentsSteer: "subagents.steer",
  subagentsFollowUp: "subagents.follow_up",
  subagentsResume: "subagents.resume",
  runtimeCommands: "runtime.commands",
  runtimeTools: "runtime.tools",
  runtimeResources: "runtime.resources",
  runtimeProcessUsage: "runtime.process_usage",
  runtimeProcessTerminate: "runtime.process_terminate",
  runtimeUserShell: "runtime.user_shell",
  toolMcp: "tool.mcp",
  toolBrowser: "tool.browser",
  toolComputer: "tool.computer",
  toolAndroid: "tool.android",
} as const;

export type StandardCapabilityName = (typeof capabilityNames)[keyof typeof capabilityNames];

/** Explicit expected-revision fence for creating a path that must not exist. */
export const workspaceEntryAbsentRevision = "workspace-entry:absent:v1";

/** Raster formats rendered side by side in Git Review. SVG stays text-only until sanitized. */
export const reviewImageRasterMimeByExtension: ReadonlyMap<string, string> = new Map([
  [".png", "image/png"],
  [".apng", "image/apng"],
  [".jpg", "image/jpeg"],
  [".jpeg", "image/jpeg"],
  [".jfif", "image/jpeg"],
  [".gif", "image/gif"],
  [".webp", "image/webp"],
  [".avif", "image/avif"],
  [".bmp", "image/bmp"],
  [".ico", "image/x-icon"]
]);

export function reviewImageMimeType(path: string): string | undefined {
  const normalized = path.replace(/\\/gu, "/");
  const name = normalized.slice(normalized.lastIndexOf("/") + 1);
  const dot = name.lastIndexOf(".");
  return dot < 0 ? undefined : reviewImageRasterMimeByExtension.get(name.slice(dot).toLowerCase());
}
